name: Deploy Worker Function


on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest        
    environment: production
    name: Deploy
    steps:
      - name: Test
        run: |
          if [ "$CF_API_KEY" == "" ]
          then
            echo "Got email"
          fi
          if [ "$CF_EMAIL" == "info@webrunes.com" ]
          then
            echo "Got secret for email"
          fi
        env: 
          CF_API_KEY: ${{env.TEST}}
          CF_EMAIL: ${{ secrets.CF_EMAIL }}
      - name: Print name
        run: echo "Hello $TEST"
      - uses: actions/checkout@v2
      - name: Publish      
        uses: cloudflare/wrangler-action@2.0.0
        with:
          apiKey: ${{ secrets.CF_API_KEY }}
          email: ${{ secrets.CF_EMAIL }}      
          wranglerVersion: '2.0.0'
          command: publish
