name: Deploy Worker Function


on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest        
    environment: production
    name: Deploy
    steps:
      - name: Test
        run: |
          if [ "$CF_API_KEY" == "" ]
          then
            echo "Got email"
          fi
          if [ "$CF_EMAIL" == "info@webrunes.com" ]
          then
            echo "Got secret for email"
          fi
        env: 
          CF_API_KEY: ${{env.TEST}}
          CF_EMAIL: ${{ secrets.CF_EMAIL }}
      - name: Print name
        run: echo "Hello $TEST"
      - uses: actions/checkout@v3
      - name: Publish      
        env:
          CF_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
          CF_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
        run: |
          npm i @cloudflare/wrangler -g
          wrangler publish
