name: Deploy Worker Function


on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest        
    environment: production
    name: Deploy
    steps:
      - name: Test
        run: |
          if [ "$CF_API_KEY" == "" ]
          then
            echo "Got email"
          fi
          if [ "$CF_EMAIL" == "info@webrunes.com" ]
          then
            echo "Got secret for email"
          fi
        env: 
          CF_API_KEY: ${{env.TEST}}
          CF_EMAIL: ${{ secrets.CF_EMAIL }}
      - uses: actions/checkout@v2
        with:
          submodules: 'true'

    # Setup npm
      - name: Setup NodeJS
        uses: actions/setup-node@v1
        with:
          node-version: '12'

    # Deploy
      - name: Deploy via CloudFlare Workers
        env:
          CF_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
          CF_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
        run: |
          npm i @cloudflare/wrangler -g
          wrangler publish
